// Generated by ReScript, PLEASE EDIT WITH CARE


var state = {
  todos: []
};

function appendTodos(todo) {
  return function (todos) {
    return {
            todos: todos.concat([todo])
          };
  };
}

function removeTodos(todoId) {
  return function (todos) {
    return {
            todos: todos.filter(function (t) {
                  return t.id !== todoId;
                })
          };
  };
}

function markCompleteTodo(todoId, completed) {
  return function (todos) {
    var todoIndex = todos.findIndex(function (todo) {
          return todo.id === todoId;
        });
    var todo = todos[todoIndex];
    if (todo === undefined) {
      return {
              todos: todos
            };
    }
    var updatedTodo_id = todo.id;
    var updatedTodo_title = todo.title;
    var updatedTodo_completed = !completed;
    var updatedTodo = {
      id: updatedTodo_id,
      title: updatedTodo_title,
      completed: updatedTodo_completed
    };
    var newTodos = todos.slice(0, todos.length);
    newTodos[todoIndex] = updatedTodo;
    return {
            todos: newTodos
          };
  };
}

function isValidTitle(val) {
  return val.replace(/\s+/g, "").length > 0;
}

function reducerFn(state, action) {
  if (typeof action !== "object") {
    return {
            todos: []
          };
  }
  switch (action.TAG) {
    case "AddTodo" :
        return appendTodos(action._0)(state.todos);
    case "RemoveTodo" :
        return removeTodos(action._0)(state.todos);
    case "MarkCompleteTodo" :
        return markCompleteTodo(action._0, action._1)(state.todos);
    
  }
}

var Todo = {
  state: state,
  appendTodos: appendTodos,
  removeTodos: removeTodos,
  markCompleteTodo: markCompleteTodo,
  isValidTitle: isValidTitle,
  reducerFn: reducerFn
};

export {
  Todo ,
}
/* No side effect */
