// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TodoListItem from "./TodoListItem.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TodoList(props) {
  var resetTodo = props.resetTodo;
  var completeTodo = props.completeTodo;
  var removeTodo = props.removeTodo;
  var todos = props.todos;
  var todoLength = todos.length;
  var isEmpty = todoLength === 0;
  if (isEmpty) {
    return JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("p", {
                            children: "No items yet"
                          }),
                      className: "h-96 flex items-center justify-center text-center text-balance rounded bg-stone-100"
                    }),
                className: "py-8"
              });
  } else {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("h2", {
                                children: "List of todos (".concat(todoLength.toString()).concat(")")
                              }),
                          todos.map(function (todo) {
                                return JsxRuntime.jsx(TodoListItem.make, {
                                            id: todo.id,
                                            title: todo.title,
                                            completed: todo.completed,
                                            removeTodo: removeTodo,
                                            completeTodo: completeTodo
                                          }, todo.id.toString());
                              })
                        ],
                        className: "pb-4"
                      }),
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("button", {
                              children: "Reset List",
                              className: "px-4 h-10 bg-red-100 rounded text-red-800",
                              onClick: (function (param) {
                                  resetTodo();
                                })
                            }),
                        className: "flex justify-end"
                      })
                ],
                className: "py-8"
              });
  }
}

var make = TodoList;

export {
  make ,
}
/* TodoListItem Not a pure module */
