// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var $$Window = {};

function TodoListItem(props) {
  var completeTodo = props.completeTodo;
  var removeTodo = props.removeTodo;
  var completed = props.completed;
  var title = props.title;
  var id = props.id;
  var checkId = React.useId();
  var label = completed ? JsxRuntime.jsx("s", {
          children: title
        }) : title;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("label", {
                                    children: label,
                                    className: "text-sm font-medium text-stone-800",
                                    htmlFor: checkId
                                  }),
                              JsxRuntime.jsx("input", {
                                    id: checkId,
                                    checked: completed,
                                    type: "checkbox",
                                    onChange: (function (param) {
                                        completeTodo(id, completed);
                                      })
                                  })
                            ],
                            className: "flex mr-auto flex-row-reverse items-center gap-x-2"
                          }),
                      JsxRuntime.jsx("button", {
                            children: "Delete",
                            className: "inline-flex text-sm font-medium items-center justify-center h-7 px-4 rounded bg-red-600 text-stone-50 hover:bg-red-400 transition",
                            onClick: (function (param) {
                                removeTodo(id);
                              })
                          })
                    ],
                    className: "py-3 px-4 flex items-center gap-x-2"
                  }),
              className: "rounded border mb-2 last-of-type:mb-0"
            });
}

var make = TodoListItem;

export {
  $$Window ,
  make ,
}
/* react Not a pure module */
