// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../modules/todo.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function TodoForm(props) {
  var addTodo = props.addTodo;
  var id = React.useId();
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var value = match[0];
  var addValidTodo = function (title) {
    var isValidTitle = Todo.Todo.isValidTitle(title);
    if (isValidTitle) {
      addTodo(title);
      return setValue(function (_v) {
                  return "";
                });
    }
    
  };
  var onKeyDown = function (e) {
    var target = e.target;
    var key = e.key;
    var value = target.value;
    if (key !== "Enter") {
      return ;
    }
    var match = typeof value;
    if (match === "string") {
      return addValidTodo(value);
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("label", {
                              children: "Todo name",
                              htmlFor: id
                            }),
                        JsxRuntime.jsx("input", {
                              className: "h-10 px-2 rounded outline-none w-full bg-stone-100 border",
                              id: id,
                              name: id,
                              placeholder: "write something for later",
                              value: value,
                              onKeyDown: onKeyDown,
                              onChange: (function (ev) {
                                  var target = ev.target;
                                  var value = target.value;
                                  setValue(function (_prevValue) {
                                        return value;
                                      });
                                })
                            })
                      ],
                      className: "w-full"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: "Submit",
                            className: "inline-flex items-center justify-center h-10 px-4 rounded bg-stone-800 text-stone-100 hover:bg-stone-900 transition",
                            onClick: (function (_e) {
                                addValidTodo(value);
                              })
                          }),
                      className: "flex justify-end pt-4 shrink-0"
                    })
              ],
              className: "flex items-end gap-x-2"
            });
}

var make = TodoForm;

export {
  make ,
}
/* react Not a pure module */
