// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./modules/todo.res.mjs";
import * as React from "react";
import * as TodoForm from "./components/TodoForm.res.mjs";
import * as TodoList from "./components/TodoList.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useReducer(Todo.Todo.reducerFn, Todo.Todo.state);
  var updateState = match[1];
  var addTodo = function (title) {
    updateState({
          TAG: "AddTodo",
          _0: {
            id: Date.now() | 0,
            title: title,
            completed: false
          }
        });
  };
  var removeTodo = function (id) {
    updateState({
          TAG: "RemoveTodo",
          _0: id
        });
  };
  var completeTodo = function ($$int, completed) {
    updateState({
          TAG: "MarkCompleteTodo",
          _0: $$int,
          _1: completed
        });
  };
  var resetTodo = function (param) {
    updateState("Reset");
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx("h1", {
                            children: "Todo Example with React and ReScript",
                            className: "text-4xl text-center font-bold text-balance"
                          }),
                      className: "pt-10 pb-4"
                    }),
                JsxRuntime.jsx(TodoForm.make, {
                      addTodo: addTodo
                    }),
                JsxRuntime.jsx(TodoList.make, {
                      todos: match[0].todos,
                      removeTodo: removeTodo,
                      completeTodo: completeTodo,
                      resetTodo: resetTodo
                    })
              ],
              className: "max-w-2xl mx-auto w-11/12"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
